# Other Matrix Operations

There are a variety of other matrix operations that are used within machine learning. Most of these are simpler than matrix multiplication, but regardless, they are important to know and use.

In [1]:
import numpy as np
import matplotlib.pyplot
from random import randomint

## Transpose

In [3]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
A.T
print(A.shape)


(2, 3)


**Problem:** Write a function that does the transpose. If you need to, try working it out by hand first and then coding.

In [7]:
def transpose(A):
    B = np.empty((A.shape[1],A.shape[0]))
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            B[j][i] = A[i][j]
    return B

In [8]:
for i in range(10):
    shape = np.random.randint(low=1, high=100, size=2)
    A = np.random.randn(*shape)
    assert np.allclose(A.T, transpose(A))
print('Success')

Success


**Problem:** Verify the first 3 properties of the matrix transpose listed in [Wikipedia](https://en.wikipedia.org/wiki/Transpose#Properties). Namely,

$$\begin{align}
\left(\mathbf {A} ^{\mathrm {T} }\right)^{\mathrm {T} }&=\mathbf {A} \quad  \\
\left(\mathbf {A} +\mathbf {B} \right)^{\mathrm {T} }&=\mathbf {A} ^{\mathrm {T} }+\mathbf {B} ^{\mathrm {T}} \\
\left(\mathbf {AB} \right)^{\mathrm {T} } &=\mathbf {B} ^{\mathrm {T} }\mathbf {A} ^{\mathrm {T} }
\end{align}$$

Use the built-in Numpy functions `A.dot(B)`, `A.T`, and `A + B` to demonstrate this numerically. Make sure you verify this for non-square matrices. Meaning ` A.shape[0] != A.shape[1] `.

In [15]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[7,8,9],[10,11,12]])
C = np.array([[7,8],[10,11],[13,14]])
def first(A):
    B = np.empty((A.shape[1], A.shape[0]))
    C = np.empty((B.shape[1], B.shape[0]))
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            B[j][i] = A[i][j] 
    for m in range(B.shape[0]):
        for n in range(B.shape[1]):
            C[n][m] = B[m][n] 
    return C

def second(A,B):
    C = np.empty((A.shape[0], A.shape[1]))
    D = np.empty((C.shape[1], C.shape[0]))
    for i in range(A.shape[0]):
        for j in range(A.shape[1]):
            C[i][j] = A[i][j] + B[i][j]
    for m in range(B.shape[0]):
        for n in range(B.shape[1]):
            D[n][m] = C[m][n] 
    return D

def third(A,B): 
    return A.dot(B).T
                

assert np.allclose(A, first(A))
assert np.allclose(A.T + B.T, second(A,B))
assert np.allclose((C.T).dot(A.T), third(A,C))

## Matrix-Vector Multiplication

A matrix times a vector is the same as a matrix times a matrix if the second matrix is a column,

In [13]:
A = np.arange(30).reshape((5, 6))
b = np.arange(6).reshape((6, 1))
print(A)
print(b)
print(A.dot(b))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[ 55]
 [145]
 [235]
 [325]
 [415]]


**Problem:** If I have a matrix $ A $ with shape `(N, M)` and multiply it by a vector $ x $. What shape must $ x $ be? What shape will $ A x $ be? Verify this numerically.

In [20]:
A = np.array([[1,2,3],[4,5,6]])
V = np.array([[1],[2],[3]])

assert np.allclose(3, V.shape[0])
assert np.allclose(1, V.shape[1])
assert np.allclose(2, A.dot(V).shape[0])
assert np.allclose(1, A.dot(V).shape[1])

## Symmetric Matrices

Symmetric matrices are such that $ S = S^T $. We can make symmetric matrices by taking any square matrix $ A $ and doing $ S = A + A^T $.

**Problem:** Verify this numerically with a few randomly generated examples and then prove it analytically.

In [30]:
A = np.array([[1,2],[4,5]])
S = np.empty((A.shape[0], A.shape[1]))
S = A + A.T
assert np.allclose(S.T, S)

SyntaxError: invalid syntax (<ipython-input-30-e3c9327bff59>, line 1)

You can also make symmetric matrices by doing $ S = A^T A $.

**Problem:** Verify this numerically with a few randomly generated examples and then prove it analytically.

In [24]:
A = np.array([[1,2],[4,5]])
S = np.empty((A.shape[0], A.shape[1]))
S = A.dot(A.T)
assert np.allclose(S.T, S)

Symmetric matrices like $ S = A^T A $ have a special property under multiplication. Namely for any vector $ z $ of the correct shape, $ z^T A^T A z \geq 0 $ regardless of the matrix $ A $.

**Problem:** Demonstrate this numerically by running random examples. If you know how, prove this analytically after.